import { CATEGORY_COLORS } from '../data/indianStates';
import { RoadCategory, StitchedRoad } from '../types';

/**
 * Sanitizes and escapes string for safe XML text & attribute insertion
 */
export function escapeXml(str: string | null | undefined): string {
  if (!str) return '';
  return String(str)
    // Remove invalid XML control characters (0x00-0x08, 0x0B, 0x0C, 0x0E-0x1F)
    .replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g, '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Formats tags into an HTML description card for Google Earth popup balloon
 */
function buildHtmlDescription(road: StitchedRoad): string {
  const parts: string[] = [];
  parts.push('<table style="border-collapse: collapse; width: 100%; font-family: sans-serif; font-size: 12px;">');
  parts.push('<thead><tr style="background: #252830; color: #fff;"><th colspan="2" style="padding: 6px 8px; text-align: left;">OSM Road Attributes</th></tr></thead>');
  parts.push('<tbody>');

  const rows: [string, string][] = [
    ['Category', CATEGORY_COLORS[road.category]?.name || road.category],
    ['Ref', road.ref || '—'],
    ['Name', road.name || '—'],
    ['Length', `${road.lengthKm.toFixed(2)} km`],
    ['OSM Way IDs', road.originalWayIds.slice(0, 10).join(', ') + (road.originalWayIds.length > 10 ? ` (+${road.originalWayIds.length - 10} more)` : '')],
  ];

  // Add remaining tags
  for (const [key, value] of Object.entries(road.tags)) {
    if (['ref', 'name', 'highway', 'geometry'].includes(key)) continue;
    rows.push([key, value]);
  }

  for (let i = 0; i < rows.length; i++) {
    const [k, v] = rows[i];
    const bg = i % 2 === 0 ? '#f7f8fa' : '#ffffff';
    parts.push(`<tr style="background: ${bg};"><td style="padding: 4px 8px; font-weight: bold; border: 1px solid #e1e4e8; width: 35%;">${escapeXml(k)}</td><td style="padding: 4px 8px; border: 1px solid #e1e4e8;">${escapeXml(v)}</td></tr>`);
  }

  parts.push('</tbody></table>');
  parts.push('<p style="font-size: 10px; color: #888; margin-top: 8px;">Data &copy; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap contributors</a> (ODbL)</p>');

  return parts.join('');
}

/**
 * Converts array of [lon, lat] coordinates to KML coordinates string format "lon,lat,0 lon,lat,0 ..."
 */
function formatCoordinates(coords: [number, number][]): string {
  return coords.map(([lon, lat]) => `${lon.toFixed(6)},${lat.toFixed(6)},0`).join(' ');
}

/**
 * Generates KML 2.2 document from array of processed StitchedRoads
 */
export function generateKml(
  roads: StitchedRoad[],
  title: string,
  stateName?: string
): string {
  const downloadDate = new Date().toISOString().split('T')[0];
  const docDescription = `OpenStreetMap Motorways & Expressways for ${stateName || title}. Downloaded on ${downloadDate}. &copy; OpenStreetMap contributors (ODbL). Generated by India Roads KMZ Exporter.`;

  const kml: string[] = [];
  kml.push('<?xml version="1.0" encoding="UTF-8"?>');
  kml.push('<kml xmlns="http://www.opengis.net/kml/2.2">');
  kml.push('  <Document>');
  kml.push(`    <name>${escapeXml(title)}</name>`);
  kml.push(`    <description>${escapeXml(docDescription)}</description>`);

  // Shared Styles
  for (const [catKey, meta] of Object.entries(CATEGORY_COLORS)) {
    kml.push(`    <Style id="style_${catKey}">`);
    kml.push('      <LineStyle>');
    kml.push(`        <color>${meta.kml}</color>`);
    kml.push(`        <width>${meta.width}</width>`);
    kml.push('      </LineStyle>');
    kml.push('      <PolyStyle>');
    kml.push(`        <color>${meta.kml}</color>`);
    kml.push('      </PolyStyle>');
    kml.push('    </Style>');
  }

  // Group roads by category
  const categories: RoadCategory[] = [
    'motorway',
    'expressway',
    'link',
    'construction',
    'proposed',
  ];

  for (const cat of categories) {
    const catRoads = roads.filter((r) => r.category === cat);
    if (catRoads.length === 0) continue;

    const catMeta = CATEGORY_COLORS[cat];
    kml.push('    <Folder>');
    kml.push(`      <name>${escapeXml(catMeta.name)} (${catRoads.length})</name>`);
    kml.push(`      <description>${escapeXml(catMeta.description)}</description>`);

    for (const road of catRoads) {
      const placemarkName = road.ref || road.name || (road.originalWayIds.length === 1 ? `Way ${road.originalWayIds[0]}` : `Road ${road.id}`);
      const descriptionHtml = buildHtmlDescription(road);

      kml.push('      <Placemark>');
      kml.push(`        <name>${escapeXml(placemarkName)}</name>`);
      kml.push(`        <styleUrl>#style_${cat}</styleUrl>`);
      kml.push(`        <description><![CDATA[${descriptionHtml}]]></description>`);

      // ExtendedData
      kml.push('        <ExtendedData>');
      kml.push(`          <Data name="category"><value>${escapeXml(cat)}</value></Data>`);
      kml.push(`          <Data name="osm_way_ids"><value>${escapeXml(road.originalWayIds.join(','))}</value></Data>`);
      kml.push(`          <Data name="length_km"><value>${road.lengthKm.toFixed(2)}</value></Data>`);
      if (road.ref) kml.push(`          <Data name="ref"><value>${escapeXml(road.ref)}</value></Data>`);
      if (road.name) kml.push(`          <Data name="name"><value>${escapeXml(road.name)}</value></Data>`);
      for (const [k, v] of Object.entries(road.tags)) {
        if (['category', 'osm_way_ids', 'length_km', 'ref', 'name'].includes(k)) continue;
        kml.push(`          <Data name="${escapeXml(k)}"><value>${escapeXml(v)}</value></Data>`);
      }
      kml.push('        </ExtendedData>');

      // Geometry: Single or MultiGeometry
      if (road.geometries.length === 1) {
        kml.push('        <LineString>');
        kml.push('          <tessellate>1</tessellate>');
        kml.push(`          <coordinates>${formatCoordinates(road.geometries[0])}</coordinates>`);
        kml.push('        </LineString>');
      } else {
        kml.push('        <MultiGeometry>');
        for (const line of road.geometries) {
          kml.push('          <LineString>');
          kml.push('            <tessellate>1</tessellate>');
          kml.push(`            <coordinates>${formatCoordinates(line)}</coordinates>`);
          kml.push('          </LineString>');
        }
        kml.push('        </MultiGeometry>');
      }

      kml.push('      </Placemark>');
    }

    kml.push('    </Folder>');
  }

  kml.push('  </Document>');
  kml.push('</kml>');

  return kml.join('\n');
}

/**
 * Generates GeoJSON FeatureCollection
 */
export function generateGeoJson(
  roads: StitchedRoad[],
  stateName?: string
): string {
  const features = roads.map((road) => {
    let geometry: { type: string; coordinates: any };
    if (road.geometries.length === 1) {
      geometry = {
        type: 'LineString',
        coordinates: road.geometries[0],
      };
    } else {
      geometry = {
        type: 'MultiLineString',
        coordinates: road.geometries,
      };
    }

    return {
      type: 'Feature',
      properties: {
        id: road.id,
        ref: road.ref,
        name: road.name,
        category: road.category,
        lengthKm: road.lengthKm,
        vertexCount: road.vertexCount,
        osmWayIds: road.originalWayIds,
        state: stateName || road.stateCode,
        ...road.tags,
      },
      geometry,
    };
  });

  return JSON.stringify(
    {
      type: 'FeatureCollection',
      name: `India_Roads_${stateName || 'Export'}`,
      crs: {
        type: 'name',
        properties: { name: 'urn:ogc:def:crs:OGC:1.3:CRS84' },
      },
      features,
    },
    null,
    2
  );
}
